when:
  event:
    - push
    - pull_request

steps:
  quality_and_performance:
    image: oven/bun:1.3.9
    commands:
      - apt-get update
      - apt-get install -y --no-install-recommends chromium
      - bun install --frozen-lockfile
      - cd apps/bedrock-template && bun install --frozen-lockfile && cd ../..
      - cd apps/astro-blog-template && bun install --frozen-lockfile && cd ../..
      - bun run ci:root
      - bun run ci:app
      - CHROME_PATH=/usr/bin/chromium bun run perf:lighthouse -- --app-dir apps/bedrock-template --skip-build --output artifacts/lighthouse/head.json
      - |
        set -euo pipefail

        ROOT_DIR="$(pwd)"
        BASE_SHA=""

        if git rev-parse --verify HEAD^ >/dev/null 2>&1; then
          BASE_SHA="$(git rev-parse HEAD^)"
        fi

        if [ -n "$BASE_SHA" ]; then
          BASE_DIR="/tmp/scryai-base"
          rm -rf "$BASE_DIR"
          git worktree add "$BASE_DIR" "$BASE_SHA"

          cd "$BASE_DIR"
          bun install --frozen-lockfile
          cd apps/bedrock-template
          bun install --frozen-lockfile
          cd ../astro-blog-template
          bun install --frozen-lockfile
          cd "$BASE_DIR"

          CHROME_PATH=/usr/bin/chromium bun run perf:lighthouse -- --app-dir apps/bedrock-template --output "$ROOT_DIR/artifacts/lighthouse/base.json"
          cd "$ROOT_DIR"

          bun run perf:lighthouse:assert -- --report artifacts/lighthouse/head.json --baseline artifacts/lighthouse/base.json
        else
          bun run perf:lighthouse:assert -- --report artifacts/lighthouse/head.json
        fi
